version: '3.8'

services:
  api:
    build:
      context: .
      target: dev
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@database:5432/postgres
      REDIS_URL: redis://:redis@redis:6379
    volumes:
      - ./src:/workout-tracker/src
      - ./prisma:/workout-tracker/prisma
    links:
      - "database:database"
      - "redis:redis"
    depends_on:
      - database
      - redis
  redis:
    image: redis:latest
    restart: always
    command: redis-server --requirepass redis
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data